### ISSUE TITLE
Embeded PDF Font Style viewed on a cell phone.

### ISSUE THREAD

**Issue by calvindebeverly** [breakfastco/embed-pdf-wpforms#2] opened 2023-11-13 03:24 UTC
I noticed that although the embeded PDF into WPforms works flawlessly on my android phone and I suspect all devices, the font looks a little squished together. Is there a way to adjust the Kerning or even the Font itself. I am satified with the work you have done. Just wondering.

Calvin De Beverly

**Comment by csalzano** [comment] 2023-11-13 17:27
Thanks for the feedback, I'll try to reproduce this problem.

**Comment by csalzano** [comment] 2023-11-14 14:50
The demo PDF embedded at https://breakfastco.xyz/embed-pdf-wpforms/ includes Helvetica Bold. Here's a screenshot from Acrobat reader: 

![Screen Shot 2023-11-14 at 9 49 06 AM](https://github.com/breakfastco/embed-pdf-wpforms/assets/938411/80367c0e-d276-4f52-a933-cb3f3919b679)

Does the text in the demo PDF look different for you?

**Comment by calvindebeverly** [comment] 2023-11-28 20:02
![370284346_363832572808987_2905633223382751239_n](https://github.com/breakfastco/embed-pdf-wpforms/assets/55323754/051ec1b9-c12d-46d8-96f5-a25f237264a6)

This is what I see on my phone as far as the letters being to close together.

**Comment by csalzano** [comment] 2023-11-28 20:30
Are you willing to share the PDF file so I can test using it?

**Comment by calvindebeverly** [comment] 2023-12-02 20:01
Sure if I can figure out how to upload it here, hum...ah attachment maybe?
[A Day in the Sun.pdf](https://github.com/breakfastco/embed-pdf-wpforms/files/13537248/A.Day.in.the.Sun.pdf)

**Comment by csalzano** [comment] 2023-12-12 15:13
I can reproduce the issue on mobile Firefox using your PDF. However, other PDFs look fine for me on mobile. I think the issue is with the font embedded in the PDF, Times New Roman PS. I found someone else with this issue: https://github.com/mozilla/pdf.js/issues/10665 

> We've managed make it work by editing the fonts within the PDF. It is currently "Times New Roman PS", re-rendering it with just "Times New Roman" seems to fix it.

I am going to close this issue because I believe the fix is create the PDF with a different font.

**Closed as completed by csalzano** 2023-12-12 15:13 UTC
Labels: wontfix

**Comment by calvindebeverly** [comment] 2023-12-16 02:56
That fixed it. I used a Verdana font. Looks great!
________________________________
